services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432"
  backend:
    image: ditod/acme-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080"
    depends_on:
      - db
    environment:
      SPRING_DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATABASE_USER: ${POSTGRES_USER}
      SPRING_DATABASE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_PROFILES_ACTIVE: prod
      SPRING_ALLOWED_ORIGIN: ${FRONTEND_ORIGIN}
    labels:
      - "traefik.http.routers.acme-backend.rule=(Host(`${HOST}`) && PathPrefix(`/api`))"
  frontend:
    image: ditod/acme-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${FRONTEND_ORIGIN}/api
    depends_on:
      - backend
    ports:
      - "80"
    labels:
      - "traefik.http.routers.acme-frontend.rule=Host(`${HOST}`)"

networks:
  default:
    name: traefik-proxy
    external: true

