/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/invoices/{invoiceId}": {
    get: operations["oneInvoice"];
    put: operations["putInvoice"];
    delete: operations["deleteInvoice"];
  };
  "/invoices": {
    get: operations["filteredInvoices"];
    post: operations["newInvoice"];
  };
  "/auth/logout": {
    post: operations["logout"];
  };
  "/auth/login": {
    post: operations["login"];
  };
  "/revenues": {
    get: operations["allRevenues"];
  };
  "/overview": {
    get: operations["overview"];
  };
  "/invoices/latest": {
    get: operations["latestInvoices"];
  };
  "/customers": {
    get: operations["filteredCustomers"];
  };
  "/customers/summary": {
    get: operations["allCustomersSummary"];
  };
  "/customer-image/{imageId}": {
    get: operations["oneCustomerImage"];
  };
  "/auth/user": {
    get: operations["authUser"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    InvoiceRequest: {
      /** Format: uuid */
      customerId?: string;
      /** Format: int32 */
      amount?: number;
      /** @enum {string} */
      status?: "pending" | "paid";
    };
    Customer: {
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** Format: uuid */
      id: string;
      name?: string;
      email: string;
      invoices: components["schemas"]["Invoice"][];
      image?: components["schemas"]["CustomerImage"];
    };
    CustomerImage: {
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** Format: uuid */
      id: string;
      contentType: string;
      blob: string[];
      customer: components["schemas"]["Customer"];
    };
    Invoice: {
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      /** Format: uuid */
      id: string;
      /** Format: int32 */
      amount: number;
      /** @enum {string} */
      status: "pending" | "paid";
      customer: components["schemas"]["Customer"];
    };
    LoginRequest: {
      email: string;
      password: string;
    };
    AuthUserDto: {
      /** Format: uuid */
      id: string;
      email: string;
      roles?: components["schemas"]["RoleSummary"][];
    };
    AuthUserResponse: {
      user?: components["schemas"]["AuthUserDto"];
    };
    PermissionSummary: {
      authority?: string;
    };
    RoleSummary: {
      name?: string;
      permissions?: components["schemas"]["PermissionSummary"][];
    };
    Revenue: {
      monthName: string;
      /** Format: int32 */
      revenue: number;
    };
    InvoiceSummaryResponse: {
      /** Format: uuid */
      id: string;
      /** Format: int32 */
      amount: number;
      name?: string;
      email: string;
      /** Format: uuid */
      imageId?: string;
    };
    OverviewResponse: {
      /** Format: int64 */
      invoiceCount: number;
      /** Format: int64 */
      customerCount: number;
      /** Format: int32 */
      totalPaidInvoices: number;
      /** Format: int32 */
      totalPendingInvoices: number;
      revenues: components["schemas"]["Revenue"][];
      latestInvoices: components["schemas"]["InvoiceSummaryResponse"][];
    };
    InvoiceFilteredPageable: {
      name?: string;
      /** Format: uuid */
      id: string;
      /** @enum {string} */
      status: "pending" | "paid";
      email: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: int32 */
      amount: number;
      /** Format: uuid */
      imageId?: string;
    };
    InvoiceFilteredResponse: {
      invoices: components["schemas"]["InvoiceFilteredPageable"][];
      /** Format: int32 */
      totalPages: number;
    };
    InvoiceBaseResponse: {
      /** @enum {string} */
      status: "pending" | "paid";
      /** Format: int32 */
      amount: number;
      /** Format: uuid */
      customerId: string;
    };
    CustomerFilteredResponse: {
      name?: string;
      /** Format: uuid */
      id: string;
      email: string;
      /** Format: uuid */
      imageId?: string;
      /** Format: int32 */
      invoicesCount: number;
      /** Format: int32 */
      pendingTotal: number;
      /** Format: int32 */
      paidTotal: number;
    };
    CustomerSummaryResponse: {
      name?: string;
      /** Format: uuid */
      id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  oneInvoice: {
    parameters: {
      path: {
        invoiceId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["InvoiceBaseResponse"];
        };
      };
    };
  };
  putInvoice: {
    parameters: {
      query: {
        newInvoice: components["schemas"]["InvoiceRequest"];
      };
      path: {
        invoiceId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Invoice"];
        };
      };
    };
  };
  deleteInvoice: {
    parameters: {
      path: {
        invoiceId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  filteredInvoices: {
    parameters: {
      query?: {
        searchQuery?: string;
        page?: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["InvoiceFilteredResponse"];
        };
      };
    };
  };
  newInvoice: {
    parameters: {
      query: {
        newInvoice: components["schemas"]["InvoiceRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Invoice"];
        };
      };
    };
  };
  logout: {
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AuthUserResponse"];
        };
      };
    };
  };
  allRevenues: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Revenue"][];
        };
      };
    };
  };
  overview: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OverviewResponse"];
        };
      };
    };
  };
  latestInvoices: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["InvoiceSummaryResponse"][];
        };
      };
    };
  };
  filteredCustomers: {
    parameters: {
      query?: {
        searchQuery?: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CustomerFilteredResponse"][];
        };
      };
    };
  };
  allCustomersSummary: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CustomerSummaryResponse"][];
        };
      };
    };
  };
  oneCustomerImage: {
    parameters: {
      path: {
        imageId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  authUser: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AuthUserResponse"];
        };
      };
    };
  };
}
