// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutDashboardIndexImport } from './routes/_layout/dashboard/index'
import { Route as LayoutDashboardCustomersImport } from './routes/_layout/dashboard/customers'
import { Route as LayoutDashboardInvoicesIndexImport } from './routes/_layout/dashboard/invoices/index'
import { Route as LayoutDashboardInvoicesNewImport } from './routes/_layout/dashboard/invoices/new'
import { Route as LayoutDashboardInvoicesInvoiceIdEditImport } from './routes/_layout/dashboard/invoices/$invoiceId.edit'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutDashboardIndexRoute = LayoutDashboardIndexImport.update({
  path: '/dashboard/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardCustomersRoute = LayoutDashboardCustomersImport.update({
  path: '/dashboard/customers',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDashboardInvoicesIndexRoute =
  LayoutDashboardInvoicesIndexImport.update({
    path: '/dashboard/invoices/',
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutDashboardInvoicesNewRoute = LayoutDashboardInvoicesNewImport.update(
  {
    path: '/dashboard/invoices/new',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutDashboardInvoicesInvoiceIdEditRoute =
  LayoutDashboardInvoicesInvoiceIdEditImport.update({
    path: '/dashboard/invoices/$invoiceId/edit',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_layout/dashboard/customers': {
      preLoaderRoute: typeof LayoutDashboardCustomersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/': {
      preLoaderRoute: typeof LayoutDashboardIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/invoices/new': {
      preLoaderRoute: typeof LayoutDashboardInvoicesNewImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/invoices/': {
      preLoaderRoute: typeof LayoutDashboardInvoicesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/dashboard/invoices/$invoiceId/edit': {
      preLoaderRoute: typeof LayoutDashboardInvoicesInvoiceIdEditImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutRoute.addChildren([
    LayoutDashboardCustomersRoute,
    LayoutDashboardIndexRoute,
    LayoutDashboardInvoicesNewRoute,
    LayoutDashboardInvoicesIndexRoute,
    LayoutDashboardInvoicesInvoiceIdEditRoute,
  ]),
  LoginRoute,
])
